project:
  type: default
  output-dir: docs

title: Thirteen* Digital Ways of Looking at -re- in Victorian Poetry
date: 11 November 2023
author: Adam Mazel, Digital Publishing Librarian
institute: Scholarly Communication Department, IUB Libraries

format: 
  revealjs:
    scrollable: true
    chalkboard: true
    overview: true
    touch: true
    progress: true
    slide-number: true
    preview-links: true
    # embed-resources: true
    fig-responsive: true
    transition: slide
    lang: en-US
    code-fold: show
    keywords: ["Digital Humanities", "Text Mining", "Victorian Poetry", "re"]
    from: markdown+emoji
preload-iframes: true
execute: 
  echo: true
  eval: true
  output: true
  error: true
output-location: slide

